### ISSUE TITLE
Nuki Binding does not work with OpenHAB 2.1

### ISSUE THREAD

**Issue by RalphSester** [mkatter/openhab2-addons#8]
Hello,

if i try to update my OpenHAB Installation from 2.0 to 2.1 the nuki-binding does not work. In the log there are the following Errors:

19:06:38.115 [ERROR] [internal.dataexchange.NukiHttpClient] - Could not handle Exception! Message[null]
java.lang.NullPointerException
        at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:525)[70:org.eclipse.jetty.client:9.2.19.v20160908]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:694)[70:org.eclipse.jetty.client:9.2.19.v20160908]
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:647)[70:org.eclipse.jetty.client:9.2.19.v20160908]
        at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:334)[70:org.eclipse.jetty.client:9.2.19.v20160908]
        at org.eclipse.jetty.client.HttpClient.GET(HttpClient.java:322)[70:org.eclipse.jetty.client:9.2.19.v20160908]
        at org.openhab.binding.nuki.internal.dataexchange.NukiHttpClient.executeRequest(NukiHttpClient.java:102)[226:org.openhab.binding.nuki:2.1.0.201705112100]
        at org.openhab.binding.nuki.internal.dataexchange.NukiHttpClient.getBridgeInfo(NukiHttpClient.java:133)[226:org.openhab.binding.nuki:2.1.0.201705112100]
        at org.openhab.binding.nuki.handler.NukiBridgeHandler.initializeHandler(NukiBridgeHandler.java:63)[226:org.openhab.binding.nuki:2.1.0.201705112100]
        at org.openhab.binding.nuki.handler.NukiBridgeHandler.lambda$0(NukiBridgeHandler.java:45)[226:org.openhab.binding.nuki:2.1.0.201705112100]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)[:1.8.0_141]
        at java.util.concurrent.FutureTask.run(Unknown Source)[:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)[:1.8.0_141]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)[:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)[:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)[:1.8.0_141]
        at java.lang.Thread.run(Unknown Source)[:1.8.0_141]

Any ideas ?

Ralph

**Comment by RalphSester** [comment]
I have checked the issue with an clean install of OpenHAB 2.1 too.
Same Errors after restart of OpenHAB.

So - the binding is not useable in OpenHAB 2.1
Is there still development activity here or is this Project dead?

Ralph

**Comment by mkatter** [comment]
@RalphSester The binding works fine for me. I'm not able to reproduce the error. Please check your Bridge configuration!
Let me know if you still experience issues.

Thanks,
Markus
